<?php

 $title = 'Add new album';
 $this->headTitle($title);
 ?>
 <div class="row">
     <div class="col-md-8">
     <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form->setAttribute('action', $this->url('album', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title')) . "<br>";
 echo $this->formRow($form->get('profile')) . "<br>";
 echo $this->formRow($form->get('artist')) . "<br>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
?>
     </div><!-- end of col-md-8 -->
 </div><!-- end of row-->